Ap/mini site graph
openclimatefix/pv-sites-mobile pull request #169
Opened 2023-03-28 20:47 UTC by anyaparekh

## Status: 
:rocket: Ready

## Description
* Add animation to site card edit mode 
* Disable the edit / done button during transitions to allow the animation to complete

Fixes #136 

## Todos
* Smoothen animations more (??)

## Screenshots
![image](https://user-images.githubusercontent.com/49364484/228363099-13450045-e3de-412f-89f1-ed1aeb7caf78.png)

2023-03-28 21:42 UTC, ericcccsliu requested changes

2023-03-28 21:42 UTC, ericcccsliu commented on components/SideBar.tsx
> +            />
Did we add these back to the sidebar? Think we don't want them there right?

2023-03-28 21:42 UTC, ericcccsliu commented on components/SiteCard.tsx
> +    console.log(displayGraph);
remove this console.log–@priyankajakka

2023-03-28 21:42 UTC, ericcccsliu commented on pages/sites.tsx
> +            }, 900);
lets set this as a constant up above this component, and export it from the file! that way, we can access it wherever else we'll need the transition duration! 🔥

2023-03-28 21:42 UTC, ericcccsliu commented on components/SiteCard.tsx
> +          } duration-[900ms] flex translate-x-40`}
reference transition duration from `sites` page

2023-03-28 21:42 UTC, ericcccsliu commented on components/SiteCard.tsx
> +              className={`w-full flex bg-amber flex-end justify-center ease-in-out transition duration-[900ms] ${
same as above

2023-03-28 21:42 UTC, ericcccsliu commented on components/SiteCard.tsx
> +              className={`w-full flex bg-[#D44545] flex-end justify-center ease-in-out transition duration-[900ms] ${
same as above

2023-03-28 21:42 UTC, ericcccsliu commented on components/SiteCard.tsx
> +          } duration-[900ms]`}
reference transition duration from `sites` page

2023-03-28 21:50 UTC, ericcccsliu commented on components/SiteCard.tsx
>          href={href}
can we disable this `href` in edit mode?

2023-03-28 21:50 UTC, ericcccsliu commented on components/SiteCard.tsx
> +              className={`w-full flex bg-[#D44545] flex-end justify-center ease-in-out transition duration-[900ms] ${
also, conditionally set `tabindex={0}` here

2023-03-28 21:50 UTC, ericcccsliu commented on components/SiteCard.tsx
> +              className={`w-full flex bg-amber flex-end justify-center ease-in-out transition duration-[900ms] ${
also set tabindex={0} here conditionally

2023-03-28 22:02 UTC, ericcccsliu approved these changes
🔥 🔥 🔥

2023-03-28 22:12 UTC, AndrewLester approved these changes
Still getting that weird negative <rect> value issue, but we can grab that later. Do you want to create an issue for that @anyaparekh?

2023-03-28 22:12 UTC, AndrewLester commented on package.json
> +    "tailwindcss": "^3.2.7"
This is there a reason `tailwindcss` was moved from the `devDependencies` section to the `dependencies` section here?

To move back:
`yarn uninstall tailwindcss`
`yarn add -D tailwindcss`

2023-03-28 22:12 UTC, AndrewLester commented on components/icons/EditIcon.tsx
> +const EditIcon: React.FC<props> = ({ color }) => (
Prefer title case for interface names.
```suggestion
interface Props {
  color: string;
}

const EditIcon: React.FC<Props> = ({ color }) => (
```

2023-03-29 18:20 UTC, ericcccsliu commented
One last thing—since you haven't merged this in yet, could you add a `.toFixed(2)` on the current output and current capacity numbers? Waaaay too many digits are displaying right now, and this really isn't part of the scope of your issue (and you didn't touch this code in any way) but it's a very trivial change that would really help us out. 
<img width="571" alt="Screen Shot 2023-03-29 at 1 19 25 PM" src="https://user-images.githubusercontent.com/62641231/228631627-fe47be79-f00b-4af7-85fc-6595f67c9ea6.png">

2023-03-30 23:44 UTC, merged