Make threshold graph interactive
openclimatefix/pv-sites-mobile pull request #179
Opened 2023-03-31 00:21 UTC by jackypark9852

## Status:
:rocket: Ready

## Description
- Makes threshold graph interactive by adding a tool tip 
- Flipped threshold line and reference line colors to make graphs and the tool tip look consistent 

Fixes #174 

## Todos

## Screenshots
![image](https://user-images.githubusercontent.com/81858354/228992430-b795e802-c1ec-413d-a12f-a82de2d00b52.png)

2023-03-31 02:31 UTC, AndrewLester approved these changes
Great work

2023-03-31 03:11 UTC, ericcccsliu requested changes
Great work, but one bug that needs to be fixed before we can merge!

2023-03-31 03:11 UTC, ericcccsliu commented on components/graphs/ThresholdGraph.tsx
> +                ) => weekdayFormatter.format(new Date(point))}
This is always giving "Wed 6:00 PM" for me 
<img width="713" alt="Screen Shot 2023-03-30 at 10 10 44 PM" src="https://user-images.githubusercontent.com/62641231/229013242-49541bb1-28ae-4bd4-b080-f1b6211d721b.png">
<img width="682" alt="Screen Shot 2023-03-30 at 10 10 52 PM" src="https://user-images.githubusercontent.com/62641231/229013267-89d77236-0060-42ae-a9fd-fd374b41c2aa.png">

2023-04-04 07:14 UTC, AndrewLester approved these changes

2023-04-08 16:06 UTC, ericcccsliu approved these changes

2023-04-09 05:19 UTC, merged