Create a hook to data formatted based on the user's local time zone
openclimatefix/pv-sites-mobile pull request #180
Opened 2023-03-31 01:15 UTC by rohanvan123

## Status: :rocket:

## Description

For this issue, the general problem was that a time increments for both graph components were based on some hard coded timezone and not the actual location of the user site. I implemented a `useDataFormatter` hook that returns the timezone, timeFormatter function, and weekdayFormatter function. These functions take in a timezone parameter. The way this parameter is obtained is through a call of Mapbox's API. This call is wrapped around a use effect which has that long and lat as dependencies. 

Fixes #147 

## Todos
- This brings up another issue, which is that the times for the threshold graph are not from 8:00 to 8:00 PM locally (they adjust based on the timezone)

## Screenshots

2023-03-31 02:32 UTC, AndrewLester approved these changes
Very nice job

2023-03-31 03:43 UTC, ericcccsliu commented
todos should be addressed and by #160

2023-03-31 03:52 UTC, ericcccsliu commented on lib/graphs.ts
> +// });
delete this comment

2023-03-31 03:52 UTC, ericcccsliu commented on lib/hooks/useDateFormatter.ts
> + * Gets forecasted and solar panel data for a single site
great having this comment here, but this line is inaccurate (copied/pasted but not changed perhaps?) and should be fixed

2023-03-31 03:52 UTC, ericcccsliu commented on lib/hooks/useDateFormatter.ts
> +  const userTimezone = data?.features[0]?.properties?.TZID ?? 'GB';
perhaps leave a comment here describing behavior when the time zone is not found—the assumption of `'GB'` might not be valid in the very long term, so we want to make clear that this is an assumption here.

2023-03-31 03:52 UTC, ericcccsliu commented on lib/hooks/useDateFormatter.ts
> +export default useDateFormatter;
absolutely great work here

2023-03-31 03:56 UTC, ericcccsliu requested changes
Looks great, great work. But, since there are still build errors happening, I can't go in and verify your changes on deployment or locally—could you fix those, address the (few) comments, and then re-request me so I can give a visual check?

2023-04-01 01:12 UTC, ericcccsliu approved these changes
lets get this merged

2023-04-01 02:19 UTC, merged