Jp/location input
openclimatefix/pv-sites-mobile pull request #21
Opened 2023-02-21 03:50 UTC by jackypark9852

# Pull Request

## Description
Create a mapbox component that allows user to input their location. 
_Please delete the italicised instruction text!
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. List any dependencies that are required for this change._

Fixes #7 

## How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration_

- [ ] Yes

_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

- [ ] Yes

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/nowcasting/blob/main/coding_style.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

2023-02-21 22:06 UTC, AndrewLester commented
@all-contributors please add @jackypark9852 for code

2023-02-21 22:06 UTC, AndrewLester commented
@all-contributors please add @ashayp22 for code

2023-02-28 03:24 UTC, AndrewLester requested changes
Great work on this! Lots of code in here and most of it is perfect. Just a few formatting/organization things really, also you can remove `package-lock.json` since our `yarn.lock` makes up for it.

2023-02-28 03:24 UTC, AndrewLester commented on components/Button.tsx
> +  children: ReactNode;
The React `PropsWithChildren` will cover this for ya

```suggestion

```

2023-02-28 03:24 UTC, AndrewLester commented on components/Button.tsx
> +import React, { ReactNode } from 'react';
Next.js makes it so `import React from 'react';` isn't required, pretty cool. Also, `PropsWithChildren` covers `ReactNode` as you'll see below.

```suggestion
import { FC, PropsWithChildren } from 'react';
```

2023-02-28 03:24 UTC, AndrewLester commented on components/Button.tsx
> +export default function Button({ children, enabled }: Props) {
Using an arrow function + `FC` type will make this type definition a bit simpler
```suggestion
const Button: FC<PropsWithChildren<Props>> = ({ children, enabled }) => {
```

2023-02-28 03:24 UTC, AndrewLester commented on components/Button.tsx
> +  }
This if can be translated into `disabled={!enabled}`. When you think about it, maybe `disabled={disabled}` could  be simpler? What do you think?
```suggestion
    return (
      <button
        disabled={!enabled}
        className="bg-ocf-gray dark:bg-ocf-gray shadow h-full w-full text-center rounded-md font-bold text-xl uppercase"
      >
        {children}
      </button>
    );
```

2023-02-28 03:24 UTC, AndrewLester commented on components/mapbox_input.tsx
> +    'pk.eyJ1IjoiYWxlc3RlcjMiLCJhIjoiY2xlM3JwdDkwMDR6cjNvdGRpanZqZHd0ciJ9.ibQNGDwEE_Wc59LB2dhs9Q';
We'll probably want to store this in an environment variable, despite it being public and fine to expose. You can put this in your `.env` and access it with `process.env.<ENV_VAR_NAME>`

2023-02-28 03:24 UTC, AndrewLester commented on components/mapbox_input.tsx
> +}: MapBoxInputProps) {
Swap this to an arrow function and use the `FC` type like above.

2023-02-28 03:24 UTC, AndrewLester commented on components/mapbox_input.tsx
> +function UpdateMarker(
Camel case

```suggestion
function updateMarker(
```

2023-02-28 03:24 UTC, AndrewLester commented on package.json
> +    "@next/font": "13.1.6",
Sadly we have to remove this since we downgraded next.js :(
```suggestion

```

2023-02-28 03:24 UTC, AndrewLester commented on pages/form.tsx
> +import Button from '~/components/Button';
```suggestion
import Button from '~/components/Button';

```

2023-02-28 03:59 UTC, AndrewLester approved these changes

2023-02-28 04:13 UTC, AndrewLester approved these changes

2023-02-28 06:13 UTC, ericcccsliu approved these changes
Looks amazing!!!!! left a few very tiny code quality suggestions. Awesome to see this map input come together—I think you absolutely knocked it out of the park with this one!!!!!!!!

2023-02-28 06:13 UTC, ericcccsliu commented on pages/test/location_input.tsx
> +  const [zoomLevelThreshold, setZoomLevelThreshold] = useState(10);
Don't really get why this is in a useState—seems like this is something we can just hardcode

2023-02-28 06:13 UTC, ericcccsliu commented on components/Button.tsx
> +      className="bg-ocf-yellow disabled:bg-ocf-gray disabled:dark:bg-ocf-gray shadow h-full w-full text-center rounded-md font-bold text-xl uppercase"
We can probably set a specific height on this button component—perhaps `h-14` could work? I don't see the height of this component changing all that much, if at all

2023-02-28 06:13 UTC, ericcccsliu commented on components/Button.tsx
> +      className="bg-ocf-yellow disabled:bg-ocf-gray disabled:dark:bg-ocf-gray shadow h-full w-full text-center rounded-md font-bold text-xl uppercase"
also maybe consider a max width—currently the button looks a big wonky as screen sizes get larger

2023-03-02 22:13 UTC, AndrewLester approved these changes

2023-03-02 22:59 UTC, ericcccsliu approved these changes
LGTM

2023-03-02 23:00 UTC, merged