Implement form context provider and post data
openclimatefix/pv-sites-mobile pull request #57
Opened 2023-03-02 21:40 UTC by anyaparekh

## Status: 
:construction: In development

## Description
* Creates custom form context and provider.
* This will allow data from both the site location page and site details page to be aggregated and posted at once when the next button on the site details page is clicked.

Fixes #45 

## Todos
* Call custom context in site location page and site details page
* Add redirect when the form is submitted

2023-03-03 06:56 UTC, ericcccsliu requested changes

2023-03-03 06:56 UTC, ericcccsliu commented on lib/context/form_context.tsx
> +  const { trigger } = useSWRMutation('/api/[...mockApiRoute]', sendRequest);
we actually want to be sending POST requests to the `/api/sites` route. also, I think we should be including the entire url here, as our API base URL will be different once we move away from mockdata. if you look in the `Graph` component there should be an example of how to use our current environment variables to specify the correct URL.

2023-03-03 06:56 UTC, ericcccsliu commented on lib/context/form_context.tsx
> +      updated_utc: 'utc_update',
these can be set right now—both can probably be set to the current time in UTC. in the future, we'll want to differentiate between creating a site and updating a site, and created_utc might well differ from updated_utc as a result, but currently, setting both to be the same thing should be fine. we'll address that once multi-site functionality is added and we gain easier access to the real API.

2023-03-03 06:56 UTC, ericcccsliu commented on lib/context/form_context.tsx
> +  const { trigger } = useSWRMutation('/api/[...mockApiRoute]', sendRequest);
ok also apparently my mock api route does not work properly—there should be a fix available when #62 gets merged in.

2023-03-03 06:56 UTC, ericcccsliu commented on lib/context/form_context.tsx
> +      installed_capacity_kw: capacity,
capacity rn might be NaN—which is falsy—as it is not required in our form. while this is the behavior we want, the API currently still doesn't allow for null capacity values. to get around this for now, lets put in an arbitrary constant "sentinel" value when the user doesn't have capacity specified.

2023-03-03 06:56 UTC, ericcccsliu commented on lib/context/form_context.tsx
> +};
great job using context wooooo  👍 🥇 💯

2023-03-03 06:56 UTC, ericcccsliu commented on lib/context/sidebar_context.tsx
> +    <SidebarContext.Provider
thanks for renaming these!!!

2023-03-03 14:25 UTC, ericcccsliu reviewed
Another comment—could we make sure that the relevant links in the sidebar link to the location input page rather than the form input page?

2023-03-03 19:28 UTC, AndrewLester requested changes
Only got a few small comments, this looks really nice. Once Eric's stuff is resolved this should be good to go.

2023-03-03 19:28 UTC, AndrewLester commented on lib/context/form_context.tsx
> +}
This can be deleted, you'll see why lower down.
```suggestion

```

2023-03-03 19:28 UTC, AndrewLester commented on lib/context/form_context.tsx
> +const FormProvider: FC<FormProviderProps> = ({ children }) => {
Instead of manually adding a type for the `children` prop, React provides one you can use in `PropsWithChildren`. You'll need to import this though.
```suggestion
const FormProvider: FC<PropsWithChildren> = ({ children }) => {
```

2023-03-04 19:02 UTC, neha-vard reviewed
This looks really good!

2023-03-04 19:02 UTC, neha-vard commented on components/NavBar.tsx
> +import { useSidebarContext } from '../lib/context/sidebar_context';
Should this import path have the same format as the import line in SideBar?

2023-03-04 19:03 UTC, anyaparekh commented on components/NavBar.tsx
> +import { useSidebarContext } from '../lib/context/sidebar_context';
yes you're right!

2023-03-04 19:14 UTC, AndrewLester approved these changes
A few small things and one consideration for later.

2023-03-04 19:14 UTC, AndrewLester commented on lib/context/form_context.tsx
> +    `${process.env.NEXT_PUBLIC_API_BASE_URL}/api/sites/`,
```suggestion
    `${process.env.NEXT_PUBLIC_API_BASE_URL}/api/sites`,
```

2023-03-04 19:14 UTC, AndrewLester commented on pages/form.tsx
> +    // ) as unknown as PanelFormDataBody;
Can be removed if we're not going with the form data system.
```suggestion

```

2023-03-04 19:14 UTC, AndrewLester commented on lib/context/form_context.tsx
> +    trigger(data);
For later: Putting the `trigger(...)` call into `setFormData` isn't invalid in any way, that is, it should work. My concern is that the function name `setFormData` implies setting some state inside the context, and maybe not actually sending the data to the API. Let me know if you agree, and we'll create a new issue to think about this later.

2023-03-04 19:32 UTC, ericcccsliu approved these changes

2023-03-04 19:32 UTC, merged